services:
  web:
    build:
        target: dev
    image: karel-web:dev
    volumes:
        - ./client:/app
        - web-node-modules:/app/node_modules
  api:
    build:
        target: dev
    image: karel-api:dev
    volumes:
        - ./server:/app
        - api-node-modules:/app/node_modules

volumes:
  web-node-modules:
  api-node-modules:
