services:
  web:
    build:
        target: dev
    image: karel-web:dev
    volumes:
        - ./client:/app
        - /app/node_modules
  api:
    build:
        target: dev
    image: karel-api:dev
    volumes:
        - ./server:/app
        - /app/node_modules
