version: '3'

services:
  db:
    image: mongo:4.2.1-bionic
    volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
  web:
    build: .
    image: kareljs-dev:latest
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
        - MONGODB_URI=mongodb://db:27017/molemarch
    ports:
        - "8000:3000"
    volumes:
        - .:/app
    depends_on:
        - db
volumes:
    mongo-data:
    mongo-config:
