version: '3'

services:
  db:
    image: mongo:4.2.1-bionic
    volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
  web:
    build:
        context: .
        dockerfile: Dockerfile.development
    image: karel-dev:latest
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
        - .:/app
    environment:
        - MONGODB_URI=mongodb://db:27017/molemarch
    ports:
      - "8000:3000"
    depends_on:
      - db

volumes:
    mongo-data:
    mongo-config:
