version: '3'

services:
  db:
    image: mongo:4.2.1-bionic
    volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
  api:
    build: ./server
    image: karel-api
    environment:
        - MONGODB_URI=mongodb://db:27017/molemarch
    ports:
        - "8081:8081"
        - "8080:8080"
        - "8000:80"
    volumes:
        - ./server:/app
        - /app/node_modules
    depends_on:
        - db
  web:
    build: ./client
    image: karel-web
    volumes:
        - ./client:/app
        - /app/node_modules
    network_mode: "service:api"
    depends_on:
        - api
  ingress:
    image: nginx:1.19-alpine
    network_mode: "service:api"
    depends_on:
        - api
        - web
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    mongo-data:
    mongo-config:
