version: '3'

services:
  db:
    image: mongo:4.2.1-bionic
    volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
  api:
    build:
        context: ./server
        target: prod
    image: karel-api:prod
    environment:
        - MONGODB_URI=mongodb://db:27017/molemarch
    ports:
        - "8081:8081"
        - "8080:8080"
        - "8000:80"
    depends_on:
        - db
  web:
    build:
        context: ./client
        target: prod
    image: karel-web:prod
    network_mode: "service:api"
  ingress:
    image: nginx:1.19-alpine
    network_mode: "service:api"
    depends_on:
        - api
        - web
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    mongo-data:
    mongo-config:
