version: '3'

services:
  db:
    image: mongo:4.2.1-bionic
    volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
  web:
    image: node:12.16
    command: /bin/bash
    # stdin_open: true
    # tty: true
    working_dir: /app
    volumes:
        - .:/app
    environment:
        - MONGODB_URI=mongodb://db:27017/molemarch
    ports:
      - "8000:3000"
    depends_on:
      - db

volumes:
    mongo-data:
    mongo-config:
