apiVersion: v1
kind: Pod
metadata:
    name: kareljs
spec:
    containers:
        - name: web
          image: gcr.io/lunch-picker-1529881352684/karel-web
          ports:
              - containerPort: 8080
        - name: api
          image: gcr.io/lunch-picker-1529881352684/karel-api
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/molemarch
          ports:
              - containerPort: 8081
        - name: ingress
          image: nginx:1.19-alpine
          ports:
              - containerPort: 80
          volumeMounts:
              - name: nginx-config
                mountPath: /etc/nginx/conf.d
    volumes:
        - name: nginx-config
          configMap:
              items:
                  - key: nginx.conf
                    path: nginx.conf
              name: kareljs
