apiVersion: apps/v1
kind: Deployment
metadata:
    name: kareljs
    labels:
        app: kareljs
spec:
    selector:
        matchLabels:
            app: kareljs
            tier: frontend
    replicas: 1
    template:
        metadata:
            labels:
                app: kareljs
                tier: frontend
        spec:
            containers:
                - name: kareljs
                  image: alpinetest:1.0
                  env:
                      - name: PORT
                        value: "80"
                      - name: MONGODB_URI
                        value: mongodb://mongo:27017/molemarch
                  ports:
                      - containerPort: 80
