apiVersion: v1
kind: Service
metadata:
    name: kareljs
spec:
    type: LoadBalancer
    loadBalancerIP: "104.198.219.39"
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: kareljs
