apiVersion: v1
kind: Service
metadata:
    name: kareljs
    labels:
        app: guestbook
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 80
    selector:
        app: kareljs
        tier: frontend
