apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb
spec:
    serviceName: mongodb
    replicas: 1
    selector:
        matchLabels:
            app: mongodb
    template:
        metadata:
            name: mongodb
            labels:
                app: mongodb
        spec:
            containers:
                - name: mongodb
                  image: mongo:4.2.1-bionic
                  ports:
                      - containerPort: 27017
                        protocol: TCP
                  volumeMounts:
                      - name: mongodb-data
                        mountPath: /data/db
    volumeClaimTemplates:
        - metadata:
              name: mongodb-data
          spec:
              resources:
                  requests:
                      storage: 1Gi
              accessModes:
                  - ReadWriteOnce
