version: '3'

services:
  db:
    image: mongo:4.2.1-bionic
    volumes:
        - mongo-data:/data/db
        - mongo-config:/data/configdb
  api:
    build: .
    image: karel-api
    environment:
        - MONGODB_URI=mongodb://db:27017/molemarch
    ports:
        - "3000:3000"
    depends_on:
        - db
volumes:
    mongo-data:
    mongo-config:
