name: Build and deploy to GKE

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: kareljs

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello
        run: echo Hello World!

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup docker credential helper
        run:
          gcloud --quiet auth configure-docker

      - name: Setup kubectl
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Build
        run: |
          TAG="$GITHUB_SHA-$GITHUB_REF"
          build () {
            context=$1
            image=$2
            docker build --tag "gcr.io/$PROJECT_ID/$image:$TAG" $context
          }
          build ./server karel-api
          build ./client karel-web

      - name: Publish
        run: |
          TAG="$GITHUB_SHA-$GITHUB_REF"
          push () {
            image=$1
            docker push "gcr.io/$PROJECT_ID/$image:$TAG"
          }
          push karel-api
          push karel-web

      - name: Deploy
        run: |
          TAG="$GITHUB_SHA-$GITHUB_REF"
          kubectl set image deployment/$DEPLOYMENT_NAME \
            web=gcr.io/$PROJECT_ID/karel-web:$TAG \
            api=gcr.io/$PROJECT_ID/karel-api:$TAG
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get svc -o wide
