name: Build and deploy to GKE

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: kareljs

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello
        run: echo Hello World!

      - name: Build
        run: |
          build () {
            context=$1
            image=$2
            docker build --tag "gcr.io/$GCP_PROJECT_ID/$image:test" $context
          }
          build ./server karel-api
          build ./client karel-web
          docker image ls
