name: Build and deploy to GKE

on:
  release:
    types: [created]

env:
  #PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: kareljs

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello
        run: echo Hello World!

      - name: multi-hello
        run: |
          echo hello1
          echo hello2

